import AtollEmbed
import Foundation

enum NotchIslandLocalization {
    static func text(_ english: String, zh: String, locale: Locale? = nil) -> String {
        isSimplifiedChinese(locale: locale) ? zh : english
    }

    static func optionalText(_ english: String?, locale: Locale? = nil) -> String? {
        english.map { atollText($0, locale: locale) }
    }

    static func atollGroups(
        _ groups: [AtollSettingGroupDescriptor],
        locale: Locale? = nil
    ) -> [AtollSettingGroupDescriptor] {
        groups.map { group in
            AtollSettingGroupDescriptor(
                id: group.id,
                title: atollText(group.title, locale: locale),
                caption: optionalText(group.caption, locale: locale),
                settings: group.settings.map { atollSetting($0, locale: locale) }
            )
        }
    }

    static func atollText(_ english: String, locale: Locale? = nil) -> String {
        guard isSimplifiedChinese(locale: locale) else { return english }
        return zhOverrides[english] ?? english
    }

    static func isSimplifiedChinese(locale: Locale? = nil) -> Bool {
        let identifier = locale?.identifier
            ?? (UserDefaults.standard.array(forKey: AppLanguagePreference.appleLanguagesDefaultsKey) as? [String])?.first
            ?? Locale.autoupdatingCurrent.identifier
        let normalized = identifier.replacingOccurrences(of: "_", with: "-")
        return normalized.hasPrefix("zh-Hans") || normalized == "zh" || normalized == "zh-CN" || normalized == "zh-SG"
    }

    private static func atollSetting(
        _ descriptor: AtollSettingDescriptor,
        locale: Locale? = nil
    ) -> AtollSettingDescriptor {
        AtollSettingDescriptor(
            id: descriptor.id,
            title: atollText(descriptor.title, locale: locale),
            description: optionalText(descriptor.description, locale: locale),
            control: atollControl(descriptor.control, locale: locale)
        )
    }

    private static func atollControl(
        _ control: AtollSettingControl,
        locale: Locale? = nil
    ) -> AtollSettingControl {
        switch control {
        case .toggle:
            .toggle
        case .slider(let min, let max, let step, let unit):
            .slider(min: min, max: max, step: step, unit: unit)
        case .picker(let options):
            .picker(options.map { option in
                AtollSettingOption(
                    value: option.value,
                    title: atollText(option.title, locale: locale)
                )
            })
        case .text:
            .text
        case .color:
            .color
        }
    }
}

private let zhOverrides: [String: String] = [
    "15 mins": "15 分钟",
    "1 hour": "1 小时",
    "3 hours": "3 小时",
    "6 hours": "6 小时",
    "12 hours": "12 小时",
    "3 items": "3 项",
    "5 colors": "5 种颜色",
    "5 items": "5 项",
    "7 items": "7 项",
    "10 colors": "10 种颜色",
    "10 items": "10 项",
    "15 colors": "15 种颜色",
    "20 colors": "20 种颜色",
    "Add depth around the expanded island.": "为展开后的刘海岛增加阴影层次。",
    "Adjusts the lock screen timer widget width without affecting button sizing.": "调整锁屏计时器组件宽度，不影响按钮尺寸。",
    "AirDrop": "隔空投送",
    "Album art parallax": "专辑封面视差",
    "Air quality scale": "空气质量标准",
    "Allow custom media button layout.": "允许自定义媒体按钮布局。",
    "Allow extension file sharing": "允许扩展文件共享",
    "Allow interactive web content": "允许交互式网页内容",
    "Allow lyric surfaces when the media source supports them.": "当媒体来源支持时显示歌词界面。",
    "Allow minimalistic overrides": "允许极简模式覆盖",
    "Appearance": "外观",
    "Assistant": "助手",
    "Atoll extension RPC/XPC event bridge.": "Atoll 扩展 RPC/XPC 事件桥接。",
    "Atoll media controls, artwork, and playback live activity.": "Atoll 媒体控制、封面和播放 Live Activity。",
    "Atoll source linked": "已连接 Atoll 源码",
    "Atoll-style lock-screen panels and widgets.": "Atoll 风格的锁屏面板和组件。",
    "Auto-hide inactive player": "自动隐藏非活跃播放器",
    "Auto-scroll to next event": "自动滚动到下一个事件",
    "Available": "可用",
    "Avoid capturing the island in screenshots and recordings.": "避免在截图和录屏中捕获刘海岛。",
    "Balanced size for media, stats, and utilities.": "适合媒体、统计和工具的均衡尺寸。",
    "Battery": "电池",
    "Battery HUDs": "电池 HUD",
    "Battery Information": "电池信息",
    "Battery, charging, and power-source live activity.": "电池、充电和电源状态 Live Activity。",
    "Behavior": "行为",
    "Blend into the top screen edge.": "融入屏幕顶部边缘。",
    "Bluetooth": "蓝牙",
    "Bluetooth Audio Devices": "蓝牙音频设备",
    "Bluetooth audio device status and connection HUD.": "蓝牙音频设备状态和连接 HUD。",
    "Brightness HUD": "亮度 HUD",
    "Browser download live activity and progress display.": "浏览器下载 Live Activity 和进度显示。",
    "CPU usage": "CPU 使用率",
    "Calendar": "日历",
    "Calendar Widget": "日历组件",
    "Calendar and reminder previews near the notch.": "在刘海附近显示日历和提醒事项预览。",
    "Calendar app": "日历应用",
    "Camera and microphone privacy indicators.": "摄像头和麦克风隐私指示。",
    "Caps Lock tint": "大写锁定色调",
    "Change Media Output control": "更改媒体输出控制",
    "Charging HUD": "充电 HUD",
    "Charging duration": "充电提示时长",
    "Choose the mirror preview shape.": "选择镜像预览形状。",
    "Choose the playback metadata provider.": "选择播放元数据来源。",
    "Choose the player slider color source.": "选择播放器滑块颜色来源。",
    "Choose previous/next track or ten-second skip.": "选择上一首/下一首或十秒快退快进。",
    "Chip color": "胶囊颜色",
    "Circle": "圆形",
    "Circular": "圆形",
    "Clipboard": "剪贴板",
    "Clipboard history surface and popover entry point.": "剪贴板历史界面和弹出入口。",
    "Color Picker": "取色器",
    "Color picker entry point and picked-colour feedback.": "取色器入口和取色反馈。",
    "Color-coded battery display": "按电量着色显示",
    "Color-coded volume display": "按音量着色显示",
    "Colored spectrograms": "彩色频谱",
    "Compact": "紧凑",
    "Countdown style": "倒计时样式",
    "Controls": "控制",
    "Copy items on drag": "拖拽时复制项目",
    "Corner radius scaling": "圆角随尺寸缩放",
    "CPU, memory, disk, network, battery, GPU, and thermal readouts.": "CPU、内存、磁盘、网络、电池、GPU 和温度读数。",
    "Customizable controls": "可自定义控制",
    "Default provider": "默认服务商",
    "Delay before hover opens the island.": "指针悬停后打开刘海岛前的延迟。",
    "Disabled": "已关闭",
    "Display": "显示",
    "Display mode": "显示模式",
    "Do Not Disturb and Focus live activity.": "勿扰模式和专注模式 Live Activity。",
    "Download Detection": "下载检测",
    "Download icon style": "下载图标样式",
    "Download indicator style": "下载指示样式",
    "Downloads": "下载",
    "Dynamic mirror": "动态镜像",
    "Enable Custom OSD": "启用自定义 OSD",
    "Enable Vertical Bar": "启用垂直条",
    "Enable Circular HUD": "启用圆形 HUD",
    "Enable diagnostics logging": "启用诊断日志",
    "Enable haptics": "启用触感反馈",
    "Enable lock screen weather": "启用锁屏天气",
    "Enable lyrics": "启用歌词",
    "Enable media panel blur": "启用媒体面板模糊",
    "Enable reminder live activity": "启用提醒事项 Live Activity",
    "Enable sneak peek": "启用快速预览",
    "Enable thinking mode": "启用思考模式",
    "Enable third-party calendar launch": "启用第三方日历启动",
    "Enable window shadow": "启用窗口阴影",
    "Enabled": "已开启",
    "Endpoint used by local model providers.": "本地模型服务商使用的端点。",
    "Event List": "事件列表",
    "Expand while the pointer is over the island.": "指针悬停在刘海岛上时自动展开。",
    "Expanded drag detection area": "扩大拖拽检测区域",
    "Extension": "扩展",
    "Extension lock screen widget capacity": "锁屏组件容量",
    "Extension notch experience capacity": "刘海体验容量",
    "Extensions": "扩展",
    "External Displays": "外接显示器",
    "Fantastical default view": "Fantastical 默认视图",
    "File shelf, AirDrop, QuickShare, and LocalSend surfaces.": "文件架、隔空投送、快速分享和 LocalSend 界面。",
    "Floating island": "悬浮岛",
    "Floating media controls": "悬浮媒体控制",
    "Float below the top edge as a detached pill.": "以独立胶囊形态悬浮在屏幕顶部下方。",
    "Focus": "专注",
    "Focus Indicator": "专注指示",
    "Focus monitoring mode": "专注监测模式",
    "Full battery duration": "满电提示时长",
    "Full battery style": "满电样式",
    "Full charge threshold": "满电阈值",
    "Fully charged HUD": "满电 HUD",
    "Fullscreen artwork on right-click": "右键显示全屏封面",
    "GPU usage": "GPU 使用率",
    "Glass mode": "玻璃模式",
    "Graph Visibility": "图表显示",
    "Height": "高度",
    "Hide all-day events": "隐藏全天事件",
    "Hide completed reminders": "隐藏已完成提醒",
    "Hide during screenshots": "截图时隐藏",
    "Hide island during screen capture": "屏幕捕获时隐藏刘海岛",
    "Hide placeholder media when playback is inactive.": "播放不活跃时隐藏占位媒体。",
    "Hide until hovered": "悬停前隐藏",
    "History size": "历史数量",
    "Hover expansion": "悬停展开",
    "HUD position": "HUD 位置",
    "Icon & Progress Color": "图标和进度颜色",
    "Icon and app icon": "下载图标和应用图标",
    "Inline HUD style": "内联 HUD 样式",
    "Inline timer controls and timer live activity.": "内联计时器控制和计时器 Live Activity。",
    "Interactive": "可交互",
    "Island": "刘海岛",
    "Island Chrome": "刘海岛外观",
    "Keep the floating pill hidden on non-notch displays until the pointer approaches.": "在非刘海显示器上保持悬浮胶囊隐藏，直到指针靠近。",
    "Keyboard Backlight HUD": "键盘背光 HUD",
    "Large": "宽大",
    "Layout": "布局",
    "Lighting effect": "光照效果",
    "Liquid Glass variant": "Liquid Glass 变体",
    "Liquid variant": "液态变体",
    "Live Activity": "Live Activity",
    "Live activity capacity": "Live Activity 容量",
    "Local model endpoint": "本地模型端点",
    "LocalSend picker style": "LocalSend 选择器样式",
    "LocalSend liquid variant": "LocalSend 液态变体",
    "Lock Screen": "锁屏",
    "Lock Screen Media": "锁屏媒体",
    "Lock Screen Timer": "锁屏计时器",
    "Lock Widgets": "锁屏组件",
    "Low battery duration": "低电量提示时长",
    "Low battery HUD": "低电量 HUD",
    "Low battery style": "低电量样式",
    "Low battery threshold": "低电量阈值",
    "Make it easier to open the island near the notch.": "让指针在刘海附近更容易打开刘海岛。",
    "Material": "材质",
    "Media": "媒体",
    "Media inactivity timeout": "媒体非活跃超时",
    "Media output": "媒体输出",
    "Memory usage": "内存使用率",
    "Metric refresh interval.": "指标刷新间隔。",
    "Minimum hover duration": "最短悬停时长",
    "Mirror & Idle": "镜像与空闲",
    "Mirror macOS Clock timers": "同步 macOS 时钟计时器",
    "Mirror shape": "镜像形状",
    "Monitoring": "监测",
    "Module": "模块",
    "Module availability is stored in TokenAtlas; Atoll-specific settings below tune behavior inside the module.": "模块可用性由 TokenAtlas 保存；下方 Atoll 专属设置用于调整模块内行为。",
    "More room for lists, shelf items, and lock-screen widgets.": "为列表、文件架项目和锁屏组件提供更多空间。",
    "Music source": "音乐来源",
    "Network activity": "网络活动",
    "Notify before": "提前提醒",
    "Off": "关闭",
    "Off by default": "默认关闭",
    "Only app icon": "仅应用图标",
    "Only download icon": "仅下载图标",
    "Open or close the island with Command-Option-N.": "使用 Command-Option-N 打开或关闭刘海岛。",
    "Open shelf tab by default": "默认打开文件架标签",
    "OSD": "OSD",
    "Padding": "内边距",
    "Parallax intensity": "视差强度",
    "Pause monitoring shortly after the island closes.": "刘海岛关闭后短暂延迟并暂停监测。",
    "Physical notch display; style is fixed to the standard notch shape.": "实体刘海显示器；样式固定为标准刘海形态。",
    "Pin the island to the main screen.": "将刘海岛固定在主屏幕。",
    "Play feedback when volume changes": "音量变化时播放反馈",
    "Play lock/unlock sounds": "播放锁定/解锁声音",
    "Play low battery alert sound": "播放低电量提示音",
    "Player color tinting": "播放器颜色染色",
    "Privacy": "隐私",
    "Privacy Indicators": "隐私指示器",
    "Progress": "进度",
    "Progress Bars": "进度条",
    "Progress style": "进度样式",
    "Progressbar style": "进度条样式",
    "Preview": "预览",
    "Quick Share": "快速分享",
    "Quick Share service": "快速分享服务",
    "Real-time waveform": "实时波形",
    "Recording": "录制",
    "Recording Indicator": "录制指示器",
    "Regular": "标准",
    "Reminder Live Activity": "提醒事项 Live Activity",
    "Remove from shelf after dragging": "拖出后从文件架移除",
    "Rest of the day": "今天剩余时间",
    "Same as notch": "跟随刘海",
    "Screen Assistant": "屏幕助手",
    "Screen assistant panels, screenshot snipping, and model chooser.": "屏幕助手面板、截图裁剪和模型选择器。",
    "Screen-recording live activity and indicator.": "屏幕录制 Live Activity 和指示器。",
    "Scroll device name": "滚动显示设备名",
    "Settings icon in notch": "刘海内显示设置图标",
    "Shared Focus Display": "共享专注显示",
    "Shelf": "文件架",
    "Shortcut bridge": "快捷键桥接",
    "Show a separate island on every connected display.": "在每个已连接显示器上显示独立刘海岛。",
    "Show all color formats": "显示所有颜色格式",
    "Show battery indicator": "显示电池指示",
    "Show battery percentage": "显示电池百分比",
    "Show battery percentage text": "显示电池百分比文字",
    "Show Caps Lock indicator": "显示大写锁定指示",
    "Show Caps Lock label": "显示大写锁定标签",
    "Show calendar countdown": "显示日历倒计时",
    "Show charging percentage": "显示充电百分比",
    "Show charging status": "显示充电状态",
    "Show clipboard icon": "显示剪贴板图标",
    "Show color picker icon": "显示取色器图标",
    "Show countdown": "显示倒计时",
    "Show event for entire duration": "在整个事件期间显示",
    "Show events within next": "显示接下来时间内的事件",
    "Show Focus as brief toast": "以短暂提示显示专注",
    "Show Focus label": "显示专注标签",
    "Show full event titles": "显示完整事件标题",
    "Show label": "显示标签",
    "Show live canvas": "显示动态画布",
    "Show location label": "显示位置标签",
    "Show lock screen media panel": "显示锁屏媒体面板",
    "Show lock screen reminder": "显示锁屏提醒",
    "Show lock screen timer widget": "显示锁屏计时器组件",
    "Show lock screen weather": "显示锁屏天气",
    "Show media app icon": "显示媒体应用图标",
    "Show next calendar event": "显示下一个日历事件",
    "Show panel border": "显示面板边框",
    "Show power status icons": "显示电源状态图标",
    "Show presets in tab": "在标签页显示预设",
    "Show progress": "显示进度",
    "Show progress percentages": "显示进度百分比",
    "Show percentages beside progress bars": "在进度条旁显示百分比",
    "Show reminder countdown": "显示提醒倒计时",
    "Show screen assistant": "显示屏幕助手",
    "Show shelf icon": "显示文件架图标",
    "Show shuffle and repeat": "显示随机和重复",
    "Show start time after event begins": "事件开始后显示开始时间",
    "Show sunrise": "显示日出",
    "Show time remaining": "显示剩余时间",
    "Show value": "显示数值",
    "Show weather AQI": "显示天气 AQI",
    "Show weather location": "显示天气位置",
    "Show weather sunrise": "显示天气日出",
    "Show weather widget": "显示天气组件",
    "Show the camera mirror surface.": "显示摄像头镜像界面。",
    "Show the idle face animation when inactive.": "非活跃时显示空闲表情动画。",
    "Show the output route button.": "显示输出路线按钮。",
    "Show the settings affordance inside the island.": "在刘海岛内显示设置入口。",
    "Size": "尺寸",
    "Skip buttons": "跳转按钮",
    "Slider color": "滑块颜色",
    "Small top pill with a focused expanded panel.": "较小的顶部胶囊和聚焦的展开面板。",
    "Sneak peek duration": "快速预览时长",
    "Sneak peek on playback changes": "播放变化时快速预览",
    "Sneak Peek style": "快速预览样式",
    "Solid colour": "纯色",
    "Source & Visibility": "来源与显示",
    "Source linked": "源码已连接",
    "Standard Notch": "标准刘海",
    "Stats": "统计",
    "Stop after closing notch": "关闭刘海后停止",
    "Temperature unit": "温度单位",
    "The default mode used when opening screen assistant.": "打开屏幕助手时使用的默认模式。",
    "Third-party Calendar": "第三方日历",
    "Thresholds": "阈值",
    "Timer": "计时器",
    "Timer control window": "计时器控制窗口",
    "Timer controls appear as": "计时器控制显示为",
    "Timer glass material": "计时器玻璃材质",
    "Timer icon color": "计时器图标颜色",
    "Timer tint": "计时器色调",
    "Timer liquid mode": "计时器液态模式",
    "Toggle the Dynamic Island open or closed from anywhere.": "从任意位置打开或关闭动态岛。",
    "TokenAtlas owns placement, sizing, and the global shortcut.": "TokenAtlas 管理位置、尺寸和全局快捷键。",
    "Use 3D Bluetooth HUD icon": "使用 3D 蓝牙 HUD 图标",
    "Use accent color": "使用强调色",
    "Use blur": "使用模糊",
    "Use colored gauges": "使用彩色仪表",
    "Use color-coded battery display": "使用按电量着色显示",
    "Use feedback on supported trackpads.": "在支持的触控板上使用触感反馈。",
    "Use MacBook icon on battery": "电池显示使用 MacBook 图标",
    "Use moving artwork/canvas inside the island.": "在刘海岛内使用动态封面/画布。",
    "Use simpler close animation": "使用简化关闭动画",
    "Use the newer close animation path.": "使用较新的关闭动画路径。",
    "Use the live audio spectrum visualizer.": "使用实时音频频谱可视化。",
    "Use the player slider color source.": "使用播放器滑块颜色来源。",
    "Use circular battery indicator": "使用圆形电量指示",
    "Vertical Bar": "垂直条",
    "Visual Effects": "视觉效果",
    "Volume HUD": "音量 HUD",
    "Volume, brightness, keyboard backlight, and custom HUD overlays.": "音量、亮度、键盘背光和自定义 HUD 覆盖层。",
    "Weather Widget": "天气组件",
    "Weather data provider": "天气数据源",
    "Width": "宽度",
    "Width adjustments apply only to the standard notch layout. Disable Minimalistic UI to edit this value.": "宽度调整仅适用于标准刘海布局。关闭极简 UI 后可编辑此值。"
]
