import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


SCRIPT = Path(__file__).resolve().parents[1] / "generate-release-history.py"


class GenerateReleaseHistoryTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp_dir = tempfile.TemporaryDirectory()
        self.repo = Path(self.temp_dir.name)
        self.output = self.repo / "ReleaseHistory.generated.swift"
        self.run_git("init")
        self.run_git("config", "user.name", "Release Bot")
        self.run_git("config", "user.email", "release@example.com")

    def tearDown(self) -> None:
        self.temp_dir.cleanup()

    def run_git(self, *args: str, date: str = "2026-05-18T12:00:00+0000") -> subprocess.CompletedProcess[str]:
        env = {
            **os.environ,
            "GIT_AUTHOR_DATE": date,
            "GIT_COMMITTER_DATE": date,
        }
        return subprocess.run(
            ["git", *args],
            cwd=self.repo,
            text=True,
            check=True,
            capture_output=True,
            env=env,
        )

    def commit(self, subject: str, body: str | None = None, date: str = "2026-05-18T12:00:00+0000") -> None:
        args = ["commit", "--allow-empty", "-m", subject]
        if body is not None:
            args.extend(["-m", body])
        self.run_git(*args, date=date)

    def tag(self, name: str) -> None:
        self.run_git("tag", name)

    def run_generator(
        self,
        tag: str,
        start_tag: str = "v1.0.0",
        *extra_args: str,
    ) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [
                sys.executable,
                str(SCRIPT),
                "--tag",
                tag,
                "--start-tag",
                start_tag,
                "--repo",
                str(self.repo),
                "--output",
                str(self.output),
                *extra_args,
            ],
            cwd=self.repo,
            text=True,
            capture_output=True,
        )

    def read_output(self) -> str:
        return self.output.read_text(encoding="utf-8")

    def seed_baseline(self) -> None:
        self.commit("feat: baseline", date="2026-05-17T08:00:00+0000")
        self.tag("v1.0.0")

    def test_generates_swift_and_escapes_strings(self) -> None:
        self.seed_baseline()
        self.commit(
            'feat: Add "quoted" path',
            '- Support C:\\Tools\\bin\n- Render "quoted" labels',
            date="2026-05-18T09:30:00+0000",
        )
        self.tag("v1.0.1")

        result = self.run_generator("v1.0.1")

        self.assertEqual(result.returncode, 0, result.stderr)
        swift = self.read_output()
        self.assertIn("// Generated by scripts/generate-release-history.py.", swift)
        self.assertIn('version: "1.0.1"', swift)
        self.assertIn('date: "May 18, 2026"', swift)
        self.assertIn('headline: "Support C:\\\\Tools\\\\bin"', swift)
        self.assertIn('Render \\"quoted\\" labels', swift)

    def test_sorts_newest_first_and_merges_duplicate_tag_commits(self) -> None:
        self.seed_baseline()
        self.commit("feat: first shared release")
        self.tag("v1.0.1")
        self.tag("v1.0.2")
        self.commit("feat: later release")
        self.tag("v1.0.10")

        result = self.run_generator("v1.0.10")

        self.assertEqual(result.returncode, 0, result.stderr)
        swift = self.read_output()
        self.assertLess(swift.index('version: "1.0.10"'), swift.index('version: "1.0.1 / 1.0.2"'))
        self.assertLess(swift.index('version: "1.0.1 / 1.0.2"'), swift.index('version: "1.0.0"'))

    def test_filters_release_bump_commits(self) -> None:
        self.seed_baseline()
        self.commit("feat: user visible change")
        self.commit("chore: 更新发布版本")
        self.tag("v1.0.1")

        result = self.run_generator("v1.0.1")

        self.assertEqual(result.returncode, 0, result.stderr)
        swift = self.read_output()
        self.assertIn("user visible change", swift)
        self.assertNotIn("更新发布版本", swift)

    def test_history_override_replaces_generated_copy(self) -> None:
        self.seed_baseline()
        self.commit("feat: generated copy should not ship")
        self.tag("v1.0.1")
        override_dir = self.repo / "release-notes" / "history"
        override_dir.mkdir(parents=True)
        (override_dir / "v1.0.1.json").write_text(
            '{\n'
            '  "headline": "Polished release headline.",\n'
            '  "changes": ["Curated first item.", "Curated second item."]\n'
            '}\n',
            encoding="utf-8",
        )

        result = self.run_generator("v1.0.1")

        self.assertEqual(result.returncode, 0, result.stderr)
        swift = self.read_output()
        self.assertIn("Polished release headline.", swift)
        self.assertIn("Curated first item.", swift)
        self.assertNotIn("generated copy should not ship", swift)

    def test_writes_history_json_without_overwriting_overrides(self) -> None:
        self.seed_baseline()
        self.commit("feat: generated release note")
        self.tag("v1.0.1")
        override_dir = self.repo / "release-notes" / "history"
        override_dir.mkdir(parents=True)
        (override_dir / "v1.0.0.json").write_text(
            '{\n'
            '  "headline": "Curated baseline.",\n'
            '  "changes": ["Keep this hand-written baseline."]\n'
            '}\n',
            encoding="utf-8",
        )

        result = self.run_generator("v1.0.1", "v1.0.0", "--write-history-json")

        self.assertEqual(result.returncode, 0, result.stderr)
        generated = json.loads((override_dir / "v1.0.1.json").read_text(encoding="utf-8"))
        preserved = json.loads((override_dir / "v1.0.0.json").read_text(encoding="utf-8"))
        self.assertEqual(generated["headline"], "generated release note")
        self.assertEqual(generated["changes"], ["generated release note"])
        self.assertEqual(preserved["headline"], "Curated baseline.")
        self.assertEqual(preserved["changes"], ["Keep this hand-written baseline."])

    def test_missing_patch_versions_are_recorded_as_skip(self) -> None:
        self.seed_baseline()
        self.commit("feat: first patch")
        self.tag("v1.0.1")
        self.commit("feat: third patch")
        self.tag("v1.0.3")

        result = self.run_generator("v1.0.3", "v1.0.0", "--write-history-json")

        self.assertEqual(result.returncode, 0, result.stderr)
        swift = self.read_output()
        self.assertLess(swift.index('version: "1.0.3"'), swift.index('version: "1.0.2"'))
        self.assertIn("third patch", swift)
        self.assertIn('version: "1.0.2"', swift)
        self.assertIn('headline: "skip"', swift)
        skip_json = json.loads((self.repo / "release-notes" / "history" / "v1.0.2.json").read_text(encoding="utf-8"))
        self.assertEqual(skip_json["headline"], "skip")
        self.assertEqual(skip_json["changes"], ["skip"])

    def test_missing_current_tag_uses_head_for_dry_run(self) -> None:
        self.seed_baseline()
        self.commit("feat: dry run release draft")

        result = self.run_generator("v1.0.1")

        self.assertEqual(result.returncode, 0, result.stderr)
        swift = self.read_output()
        self.assertIn('version: "1.0.1"', swift)
        self.assertIn("dry run release draft", swift)


if __name__ == "__main__":
    unittest.main()
