// Generated by scripts/generate-release-history.py. Do not edit by hand.

extension ReleaseHistoryCatalog {
    static let generatedEntries: [ReleaseHistoryEntry] = [
        ReleaseHistoryEntry(
            version: "1.0.0",
            date: "May 26, 2026",
            headline: "重新定位为精简后的新产品起点",
            changes: [
                "以精简后的应用形态作为新的版本基线",
                "版本号从 1.0.0 重新开始，构建号重置为 1",
                "移除旧发布历史中已经下线的功能叙事",
                "后续 Git 历史等待重新初始化后再按新基线提交",
            ]
        ),
    ]
}
